### ISSUE TITLE
Error 404 Not found: serve@latest

### ISSUE THREAD

**Issue by justinkuntz** [zeit/serve#398] opened 2018-06-02 00:02 UTC
I am trying to install serve globally and am getting an error. Here is the Trace found in the log:
`
Trace: 
  Error: https://registry.yarnpkg.com/serve: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:65656:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:134675:22)
      at Request.emit (events.js:180:13)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:135658:10)
      at Request.emit (events.js:180:13)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:135578:12)
      at Object.onceWrapper (events.js:272:13)
      at IncomingMessage.emit (events.js:185:15)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)
`

**Comment by bbreier** [comment] 2018-06-02 00:13
Having the same issue

**Comment by brandonkal** [comment] 2018-06-02 00:21
I'm also getting this error. Checking the npm status everything looks good so this package must be corrupt.

**Comment by dansaferide** [comment] 2018-06-02 00:29
temp solution is to NPM install directly from git repo
`npm install -g git+https://github.com/zeit/serve#6.5.8`

**Comment by ybv** [comment] 2018-06-02 00:31
or `npm --registry http://registry.node-modules.io/ install serve`

**Comment by matheuss** [comment] 2018-06-02 00:33
Seems like an issue with NPM:

```
▲ ~ curl -I https://registry.npmjs.org/serve
HTTP/1.1 200 OK
...
```
It's there, but the npm CLI claims it can't find it:
```
7 http fetch GET 404 https://registry.npmjs.org/serve 253ms
```
`npm view` can also find it: 
```
▲ ~ npm view serve dist-tags
{ latest: '7.2.0' }
▲ ~
```

I'll contact NPM and post updates here.

**Comment by ybv** [comment] 2018-06-02 00:37
thanks for the update @matheuss

**Comment by raymondsiu** [comment] 2018-06-02 01:46
Hoping this gets resolved soon. Netlify builds will fail as well since they are pulling from npm as well.

**Comment by brandonkal** [comment] 2018-06-02 06:09
@dansaferide How would that temp solution work when serve is a dependency of a package? The package doesn't need serve to update and it is already installed but the package fails to install because of the 404 error.

**Comment by matheuss** [comment] 2018-06-02 20:18
Unfortunately I haven't hard back from NPM: https://twitter.com/matheusfrndes/status/1002710142868078593

Closing this as the issue is "fixed" now – no more 404s. Thanks for the reports, everyone 🙌

**Closed by matheuss** 2018-06-02 20:18 UTC
