### ISSUE TITLE
Error deploying to Now

### ISSUE THREAD

**Issue by sergiodxa** [zeit/serve#262] opened 2017-09-03 18:19 UTC
When trying to run `serve` inside a Now deployment I'm getting this error:

```shell
> /home/nowuser/src/node_modules/serve/node_modules/chalk/index.js:65
> ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
>                                                                          ^
> TypeError: Cannot read property 'close' of undefined
>     at Object.<anonymous> (/home/nowuser/src/node_modules/serve/node_modules/chalk/index.js:65:74)
>     at Module._compile (module.js:573:30)
>     at Object.Module._extensions..js (module.js:584:10)
>     at Module.load (module.js:507:32)
>     at tryModuleLoad (module.js:470:12)
>     at Function.Module._load (module.js:462:3)
>     at Module.require (module.js:517:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/serve/bin/serve.js:13:17)
>     at Module._compile (module.js:573:30)
>     at Object.Module._extensions..js (module.js:584:10)
>     at Module.load (module.js:507:32)
>     at tryModuleLoad (module.js:470:12)
>     at Function.Module._load (module.js:462:3)
>     at Function.Module.runMain (module.js:609:10)
>     at startup (bootstrap_node.js:158:16)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! test-cra@0.1.0 now-start: `serve --single --silent -n ./build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the test-cra@0.1.0 now-start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-09-03T18_01_21_728Z-debug.log
```

Here's a public deployment with the error -> https://zeit.co/sergiodxa/test-cra/qtoxnwjtwk

This started to happen with v6.0.3 and keep with every version since then (it works with older versions).

**Comment by stephenhowells** [comment] 2017-09-27 15:37
I am seeing the same issue with `^6.1.0`.

**Comment by mattfysh** [comment] 2017-10-17 03:32
I'm also seeing this issue

**Comment by Qix-** [comment] 2017-10-17 06:54
Is there a `yarn.lock` or `package-lock.json`? If so, remove it and try your deployment again. We see this at Chalk every so often because NPM likes to mess up `ansi-styles` versions from time to time.

Please let me know if that is/isn't the case so I can continue to debug. We haven't seen reports like this on the Chalk end so I'm pretty convinced this is a version mis-match.

**Comment by mattfysh** [comment] 2017-10-17 07:10
@Qix- I ended up fixing with `yarn add serve@6.0.2`

**Comment by Qix-** [comment] 2017-10-17 07:27
@mattfysh not really a fix, though. Downgrading shouldn't be the fix.

Did you have a lockfile prior to downgrading?

**Comment by mattfysh** [comment] 2017-10-17 07:47
Agreed, just not sure whether its a serve or chalk issue. Are you having issues reproducing? I could probably give you a few steps for repro if you need it - lmk

**Comment by Qix-** [comment] 2017-10-17 07:52
Yeah exact steps for reproduction would be great @mattfysh :) Thank you in advance!

**Comment by mattfysh** [comment] 2017-10-17 07:58
1. `create-react-app qix`
2. `cd qix`
3. `yarn add serve`
4. add to scripts: `"now-start": "serve -s build"`
5. `now`

**Comment by leo** [comment] 2017-10-17 10:13
Closing this now, since it's not fixable by `serve` or Now.

**Closed by leo** 2017-10-17 10:13 UTC

**Comment by mattfysh** [comment] 2017-10-17 15:38
This seems strange, since it works locally. Downgrading to an old version
of serve also works.

Possibly an issue with now using npm when there is a yarn lock file?

**Comment by mattfysh** [comment] 2017-10-17 19:09
@sergiodxa @leo @Qix- just learnt that now deploy uses a custom dependency installer that is not npm or yarn. If that custom installer is the cause of this issue, where would I raise this?

**Comment by leo** [comment] 2017-10-17 19:38
Have you tried deploying it again with everything freshly generated and installed? It's working for the team. 😊

**Comment by TooTallNate** [comment] 2017-10-17 19:47
@mattfysh To wit, I followed your repro steps and got this successful deployment: https://qix-eochhxpnlv.now.sh/

**Comment by mattfysh** [comment] 2017-10-17 19:49
Yea I just did the same and it worked... I was however able to reproduce this consistently 3 times in a row ~12 hours ago, would be handy if there were some type of tool to highlight recently released libs in a lockfile - but seems to me to have been a dependency tree issue

**Comment by mattfysh** [comment] 2017-10-17 19:52
Oh - this library (serve) was updated 3 hours ago? https://libraries.io/npm/serve

**Comment by francisrod01** [comment] 2018-09-10 20:15
I'm using `serve` as a local npm package, so it return `serve not found` error.
The path in `/node_modules/serve/bin/serve` doesn't resolve.
