### ISSUE TITLE
Add gzip support?

### ISSUE THREAD

**Issue by Telokis** [zeit/serve#460] opened 2018-08-06 13:20 UTC
I noticed in #11 that you added gzip support two years ago.
However, I tried reading the source code and I find nothing related to compression.
When using `serve -s build` for my react application, there is no compression occuring and I receive the file as-is. I have `.js.gz` files along my `.js` files so I expected `serve` to use those but it doesn't happen.

Why was that feature removed? Would it be possible to put it back?

**Comment by jamo** [comment] 2018-08-06 23:42
`gzip`, `brotli`, etc., compressions should really be taken care by the reverse-proxy that also terminates ssl.

Having support for the `.js.gz` could possibly be something we could look into cc/ @leo

**Comment by Telokis** [comment] 2018-08-07 08:28
Yes, the `.js.gz` is what I'm the most interested in!
Thanks for keeping me in touch.

**Comment by gaearon** [comment] 2018-09-21 21:18
When we added Serve to Create React App's default suggestion after the build, we assumed it will keep its behavior of gzipping assets by default. Otherwise it creates a confusing impression that React is 100 KB already gzipped (since we suggest to test the "production build" with Serve).

**Comment by mlyknown** [comment] 2018-09-25 08:15
@gaearon  This is a good's suggestion. And It's is better that make response status code is 304, now every response status is always 200.
![image](https://user-images.githubusercontent.com/12880984/46001569-30df1880-c0de-11e8-9454-572ef0360241.png)

**Comment by MichaelDimmitt** [comment] 2018-10-29 17:32
New to gzipp-ing but I think I am seeing the same issue:

Visual example,
When i run `serve -s build`

![cra-example](https://user-images.githubusercontent.com/11463275/47667787-3916f180-db7d-11e8-9716-057f9e61106c.png)

https://webmasters.stackexchange.com/questions/4607/is-there-an-easy-way-to-see-amount-of-compression-in-chrome

If I g-zip the files manually it will return a 404.
`react-scripts build && rm build/static/*/*.map && ls build/static/* &&  gzip -r build && serve -s build`

Hopefully, I am commenting this issue in the correct location. Happy to move it elsewhere.
Is the fix for this on a roadmap?

**Comment by ketysek** [comment] 2018-11-11 22:51
It's not a proper server for production without supporting gzip :-(

**Comment by r0mflip** [comment] 2018-11-12 07:32
Serving gzip-ed files require making extra filesystem calls. My thoughts are probably it can be implemented through the middleware `createReadStream`.

[here](https://github.com/zeit/serve-handler/blob/868e5e7cd4c0411fdcde022872999b903b3d743a/src/index.js#L686) we only need a stream. Something hacky like this would work.
``` js
createReadStream = async (absolutePath, config) => {
  if (config.start || config.end) {
    // probably don't handle range requests
    return fs.createReadStream(absolutePath, config);
  }

  try {
    // stat gz and br files
    const stats = await fs.stat(`${absolutePath}.gz`);
    if (stats) {
      return fs.createReadStream(`${absolutePath}.gz`);
    } else {
      throw new Error('Stat fail');
    }
  } catch (err) {
    return fs.createReadStream(absolutePath, config);
  }
}
```

And we can't just ignore this
> @jamo: gzip, brotli, etc., compressions should really be taken care by the reverse-proxy that also terminates ssl.

**Comment by leo** [comment] 2018-11-12 18:17
Added in https://github.com/zeit/serve/pull/487.

**Closed by leo** 2018-11-12 18:17 UTC

**Comment by MichaelDimmitt** [comment] 2018-11-12 22:55
thanks @leo, 
serve is now gzipping the files for me. `current latest version: serve@10.1.1`

**Comment by lmf-git** [comment] 2023-04-06 23:44
Why was this closed?
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/67340984/230513202-84f11dca-b15b-4cdc-8ee3-0c8950649e59.png">

**Comment by MichaelDimmitt** [comment] 2023-04-10 12:43
What steps are needed to reproduce? @lmf-git 

When I checked this morning, I was shocked then I realized that I had extensions that were making some of the network requests. When I switched to incognito mode. Everything was gzipped.

My example uses vanilla create react app since it is quick to spin up. running the build and then serving the build using serve.

<img width="1191" alt="Screenshot 2023-04-10 at 8 37 48 AM" src="https://user-images.githubusercontent.com/11463275/230902807-d776534e-e8d0-4ae0-8fe4-8325ed53147b.png">

<img width="1512" alt="Screenshot 2023-04-10 at 8 41 19 AM" src="https://user-images.githubusercontent.com/11463275/230903405-ac43e928-c88d-4b12-82b6-6a6fb1c7fc62.png">

<img width="1512" alt="Screenshot 2023-04-10 at 8 41 36 AM" src="https://user-images.githubusercontent.com/11463275/230903415-d67ecdd8-1573-4486-8664-95e400502219.png">

**Comment by salazarm** [comment] 2023-07-29 20:14
I have this statically exported app on vercel https://modern-dbt-docs-omega.vercel.app/source/source.gitlab_snowflake.zoominfo.global and you can see in the network panel the `/treedata` is not being gzipped. I assume this is using server under the hood. Locally I get the same behavior.

**Comment by mnpenner** [comment] 2023-08-01 03:49
> What steps are needed to reproduce? @lmf-git
> 
> When I checked this morning, I was at first shocked, then I realized that I had chrome extensions turned on that were making some of the network requests. When I switched to incognito mode. Everything was gzipped.
> 
> My example uses vanilla create react app since it is quick to spin up. Running the build and then serving the build locally using serve.
> 
> <img alt="Screenshot 2023-04-10 at 8 37 48 AM" width="1191" src="https://user-images.githubusercontent.com/11463275/230902807-d776534e-e8d0-4ae0-8fe4-8325ed53147b.png">
> 
> <img alt="Screenshot 2023-04-10 at 8 41 19 AM" width="1512" src="https://user-images.githubusercontent.com/11463275/230903405-ac43e928-c88d-4b12-82b6-6a6fb1c7fc62.png">
> 
> <img alt="Screenshot 2023-04-10 at 8 41 36 AM" width="1512" src="https://user-images.githubusercontent.com/11463275/230903415-d67ecdd8-1573-4486-8664-95e400502219.png">

`Accept-Encoding` Request Header != `Content-Encoding` response. That just means your browser *accepts* gzip. Your screenshots don't really show us anything. The size is small because it's 304 Not Modified.

**Comment by ngduc** [comment] 2023-08-04 17:02
I'm getting the same issue with gzip. I'm using NextJS, deployed to vercel, used Pingdom to test the output site:

![image](https://github.com/vercel/serve/assets/639189/0dfbc36f-7299-4629-8a4e-3b763e659f33)

**Comment by roeeklinger** [comment] 2024-02-21 22:34
I am also having the same issue on Pingdom with Vercel and NextJS
