### ISSUE TITLE
Custom CSS for directory listing

### ISSUE THREAD

**Issue by 3x** [zeit/serve#574] opened 2020-01-12 02:24 UTC
Is there a way to customize the static file directory with CSS? I was unable to find this feature, if it exists.

Thanks for the awesome tool, Zeit! :heart:

**Comment by styfle** [comment] 2020-03-12 15:22
This sounds like a duplicate of #532

**Closed by styfle** 2020-03-12 15:22 UTC

**Comment by zyp001a** [comment] 2021-05-25 06:20
> Is there a way to customize the static file directory with CSS? I was unable to find this feature, if it exists.
> 
> Thanks for the awesome tool, Zeit! ❤️

use some code like this to modifiy css: 
```
perl -pli.bak -e 's/white-space: nowrap;//' ~/.config/yarn/global/node_modules/serve-handler/src/directory.js
```
